[ids]

*

[main]

# Set numbers and symbols as Dvorak programmer
` = $

1 = &
2 = [
3 = {
4 = }
5 = (
6 = =
7 = *
8 = )
9 = +
0 = ]

[ = !
= = #
] = @


# Key used to include temporary macros in the 'main' layer:
# Comment/uncomment to enable/disable it
# Save the buffer, go to Chromium, and hard reload (refresh server)
# f7 = macro(C-s 100ms f12 200ms C-S-r)


# Switches to other layers and macro keys (PrtScn/SysRq key)
sysrq = oneshot(central)


# Enable sticky keys
# Latching (first press activates modifier's layer for next key)
control = oneshot(control)
shift = oneshot(shift)
meta = oneshot(meta)
alt = oneshot(alt)

# Locking (second press locks modifier until pressed again)
[control]

control = toggle(control)

[shift]

shift = toggle(shift)

# Set numbers and symbols as Dvorak programmer
` = ~

1 = %
2 = 7
3 = 5
4 = 3
5 = 1
6 = 9
7 = 0
8 = 2
9 = 4
0 = 6

[ = 8
= = `
] = ^

[meta]

meta = toggle(meta)

[alt]

alt = toggle(alt)


# Switches to other layers and macro keys (PrtScn/SysRq key)
[central]

d = toggle(design)
e = toggle(english)

# MACROS

# Copy a sentence from Translate and paste in a new Emacs Org header (chromium)
3 = macro(f5 100ms C-enter 50ms C-v 500ms f12 400ms A-j 400ms f5 100ms C-c C-b 50ms C-c C-f 50ms C-right 50ms C-left 50ms C-v 50ms enter)

# Copy a sentence from Translate and paste in a new Emacs Org header (chrome)
4 = macro(f5 100ms C-enter 50ms C-v 500ms M-7 400ms A-j 400ms f5 100ms C-c C-b 50ms C-c C-f 50ms C-right 50ms C-left 50ms C-v 50ms enter)

# Save the buffer, go to Chromium, and reload (refresh server)
= = macro(C-s 50ms f12 200ms C-r)
# Save the buffer, go to Chromium, reload, and return last wind (refresh server)
- = macro(C-s 50ms f12 200ms C-r 100ms f5)
# Go to Chromium, reload, and return to the last window
# = = macro(f12 100ms C-r 100ms C-$)

# Key used to include temporary macros in the 'central' layer:
# Save buffer, go to Chromium, hard reload, and return last wind (refresh server)
delete = macro(C-s 50ms f12 200ms C-S-r 100ms f5)
# Select and remove text in the js file and paste the last clipboard text
# delete = macro(C-a backspace M-t S-insert)


# To use design programs with default modifier behavior
[design]

control = layer(controlmod)
shift = layer(shiftmod)
alt = layer(altmod)

f7 = leftmouse
compose = rightmouse

[controlmod:C]

[shiftmod:S]

# Set numbers and symbols as Dvorak programmer
` = ~

1 = %
2 = 7
3 = 5
4 = 3
5 = 1
6 = 9
7 = 0
8 = 2
9 = 4
0 = 6

[ = 8
= = `
] = ^

[altmod:A]


# To practice with Google Translate
[english]

# / -> / , ] -> @ , \ -> \ , = -> # , [ -> !, - -> - (keys in dvorak)
# Google Translate speaks (google speaks)
/ = A-k
# Google Translate listen (user speaks microphone)
] = A-x
# Google Translate switch
\ = A-e
# Google Translate clear
[ = A-i
# Google Translate focus
= = A-u
# Google Translate copy
- = A-j

# 1 -> & , 2 -> [ , 3 -> { , 4 -> } (keys in dvorak)
# GoogleTranslate speaks a sentence, and switches to Emacs and fold the header
1 = macro(A-k 50ms f5 100ms tab)

# GoogleTranslate speaks a sentence, switches to Emacs, folds the header,
# moves to the next, folds it, and places the cursor at the beginning
2 = macro(A-k 50ms f5 100ms tab 50ms C-c C-n 50ms tab 50ms C-right 50ms C-left)

# Copy a sentence from Translate and paste in a new Emacs Org header (chromium)
3 = macro(f5 100ms C-enter 50ms C-v 500ms f12 400ms A-j 400ms f5 100ms C-c C-b 50ms C-c C-f 50ms C-right 50ms C-left 50ms C-v 50ms enter)

# Copy a sentence from Translate and paste in a new Emacs Org header (chrome)
4 = macro(f5 100ms C-enter 50ms C-v 500ms M-7 400ms A-j 400ms f5 100ms C-c C-b 50ms C-c C-f 50ms C-right 50ms C-left 50ms C-v 50ms enter)
